version: "3.5"

networks:
  proxy:
    external: true
  default:
    driver: bridge

services:
  web:
    image: nginx:latest
    container_name: codewars_web
    ports:
      - 80:80
    labels:
      - "traefik.frontend.rule=Host:codewars.traefik.localhost"
      - "traefik.docker.network=proxy"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: docker/php
    container_name: codewars_php
    volumes:
      - .:/var/www/html:cached
    expose:
      - 9001
    ports:
      - "9000:9000"
    environment:
      - PHP_XDEBUG_ENABLED=1
      - APP_ENV=${APP_ENV}

  selenium-hub:
    image: selenium/hub:3.141.59-titanium
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"